SELECT DISTINCT (1000) [Country]
      ,[Province]
      ,[City]
      ,[Property_Price]
      ,[Bedrooms]
      ,[Bathrooms]
      ,[Parking]
      ,[Floor_size]
      ,[Monthly_repayment]
      ,[Total_once_0ff_cost]
      ,[Min_Gross_Monthly_income]
  FROM [property25].[dbo].[Property_Details]
